version: "3"

services:
  mongodb:
    image: mongo
    container_name: 'corider_mongo'
    ports:
      - "27017:27017"
    volumes:
      - coriderdb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

volumes:
  coriderdb:

